### ISSUE TITLE
Grab tool not working

### ISSUE THREAD

**Issue by ErkBlender** [the3dadvantage/Modeling-Cloth#1]
@the3dadvantage 
I tried it and it worked really well, except for the grab tool. I tried clicking around and pulling but it just didn't work. I really love the addon, it really speeds up cloth stuff. Thanks :)

btw is there a feature to collide with other objects? that would be amazing ;)

**Comment by the3dadvantage** [comment]
I think it's because object transforms are not applied. With the location rotation and scale cleared it works. I'll have to look into it.

**Comment by the3dadvantage** [comment]
Applied transforms
