### ISSUE TITLE
Instalation (Sorry for noob Question)

### ISSUE THREAD

**Issue by moahrs** [the3dadvantage/Modeling-Cloth#24]
Hello,

Sorry about this noob question. Where I put this in the blender? Directory/Folder?

Thanks a Lot,
Moacir Jr.

**Comment by the3dadvantage** [comment]
In Blender's user preferences there is an option to install addons. You can install the zip folder directly.
Go into addons and look for the "install from file" option (I think that's what it's called.)
Cheers!

**Comment by moahrs** [comment]
Thank you
