### ISSUE TITLE
Seg fault for collada_export

### ISSUE THREAD

**Issue by djkmiles** [the3dadvantage/Modeling-Cloth#4]
Blender 2.79 with macOS Sierra and with High Sierra crashing, minimal re-create is activate modeling_cloth to plane and attempt default collada export.

**Comment by djkmiles** [comment]
Currently no work-around is found, even disabling the add-on before export causes the crash. Do you have any advice?

**Comment by djkmiles** [comment]
Only further detail that can be provided at the moment is that the seg-fault/bug can be isolated down to presence of either shape-keys aside from Basis. The data causing corruption must exist in shape keys. Deleting all shape-keys other than the default Basis one mitigates the error. This is a significant bug, as it corrupts the entire scene.

<img width="365" alt="screen shot 2018-01-27 at 16 18 21" src="https://user-images.githubusercontent.com/5477701/35473880-1aeae1da-037e-11e8-8a11-1ce2b40fbbd9.png">

A positive contribution is that this has been tested with the current Kronos glTF exporter with no problems.

**Comment by djkmiles** [comment]
OK 👌 I've got a decent work-around for this! The crash only happens with built-in DAE exporter, not FBX or glTF. It only occurs with default exporter when shape-keys are enabled. Simply not exporting shape keys avoids that totally.

However, if shape keys are important to the export, there is this excellent add-on from the GoDot Engine repo, "Better Collada Exporter" which works just fine:

https://github.com/godotengine/collada-exporter

Worth noting that "Shape Keys" are off by default with the GoDot improved DAE exporter. The problem might well be with the default DAE exporter, not this add-on.

**Comment by the3dadvantage** [comment]
Collada export fails for any object with shape keys. Just do a new shape from mix, then collapse all shape keys before export.
