### ISSUE TITLE
Gravity vector along object-Z, not world-Z

### ISSUE THREAD

**Issue by robw001** [the3dadvantage/Modeling-Cloth#5]
Hi Rich,

The gravity vector seems to be along object-Z, not world-Z. This is a bit confusing. I would expect gravity to follow world-Z.

To reproduce: take the default cube, rotate x*45, mark as Modeling Cloth, set gravity, hit Play.

Is it possible to set the gravity vector to world-Z, or even better: set a custom vector?

Regards,

Rob.

**Comment by the3dadvantage** [comment]
For now I'm ignoring object transforms. It would make more sense to use world coordinates and that's easy enough to implement. I will change this when I start working on object collisions. Hopefully this week.

**Comment by robw001** [comment]
Thanks! :)

**Comment by the3dadvantage** [comment]
Fixed! Now gravity is global and even updates in real time while rotating an object

**Comment by robw001** [comment]
Awesome. I'll go and experiment :)

**Comment by robw001** [comment]
Checked: works beautifully.
